image: python:latest

run:
  script:
    - pip install twine
    - python setup.py bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  artifacts:
    paths:
      - dist/*.whl
  only:
  - main

build_pages:
  stage: build
  script:
  - pip install -U sphinx sphinx-rtd-theme sphinx-prompt
  - sphinx-build -W -n -b html docs public
  only:
  - merge_requests

pages:
  stage: deploy
  script:
  - pip install -U sphinx sphinx-rtd-theme sphinx-prompt
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
  - main
